apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal
  template:
    metadata:
      labels:
        app: personal
    spec:
      containers:
        - name: personal
          image: lusalvi/personal:latest
          ports:
            - containerPort: 3000
          env:
            - name: SUPABASE_URL
              value: "https://clrawvfedwpywhdcckok.supabase.co"
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: api-key