apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehiculos
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehiculos
  template:
    metadata:
      labels:
        app: vehiculos
    spec:
      containers:
        - name: vehiculos
          image: lusalvi/vehiculos:latest
          ports:
            - containerPort: 3000
          env:
            - name: SUPABASE_URL
              value: "https://clrawfedwpvywhdcclk.supabase.co"
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SUPABASE_KEY