apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      lusalvi/frontend:values=values-dev.yaml,tag=frontend.tag
      lusalvi/personal:values=values-dev.yaml,tag=personal.tag
      lusalvi/vehiculos:values=values-dev.yaml,tag=vehiculos.tag
    argocd-image-updater.argoproj.io/frontend.update-strategy: semver
    argocd-image-updater.argoproj.io/frontend.allow-tags: ^dev-v[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/frontend.pull-policy: Always
    argocd-image-updater.argoproj.io/personal.update-strategy: semver
    argocd-image-updater.argoproj.io/personal.allow-tags: ^dev-v[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/personal.pull-policy: Always
    argocd-image-updater.argoproj.io/vehiculos.update-strategy: semver
    argocd-image-updater.argoproj.io/vehiculos.allow-tags: ^dev-v[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/vehiculos.pull-policy: Always
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-credentials: git-creds
spec:
  project: default
  source:
    repoURL: https://github.com/lusalvi/nuvexa-k8s.git
    targetRevision: main
    path: charts/nuvexa
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
      parameters:
        - name: component
          value: frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
