apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lusalvi/nuvexa-k8s.git
    targetRevision: main
    path: charts/nuvexa
    helm:
      valueFiles:
        - values.yaml
        - values-test.yaml
      parameters:
        - name: component
          value: frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true