{{- $name := .Values.component }}
{{- $config := index .Values $name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ $name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ $config.image }}
          ports:
            - containerPort: {{ $config.port }}
          {{- if eq $name "vehiculos" }}
          env:
            - name: SUPABASE_URL
              value: {{ $config.supabase.url }}
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $config.supabase.secretName }}
                  key: {{ $config.supabase.secretKey }}
          {{- end }}