apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nuvexa-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewrite }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .service }}-service
                port:
                  number: {{ .port }}
          {{- end }}