{{- $name := .Values.component }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ $name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  {{- if eq $name "frontend" }}
  type: NodePort
  nodePort: {{ .Values.nodePort }}
  {{- end }}