apiVersion: v1
kind: Service
metadata:
  name: {{ include "nuvexa.fullname" . }}
  labels:
    {{- include "nuvexa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nuvexa.selectorLabels" . | nindent 4 }}
