{{- $name := .Values.component }}
{{- $config := index .Values $name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ $name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ $name }}
  {{- if eq $name "frontend" }}
  type: NodePort
  {{- end }}
  ports:
    - protocol: TCP
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
      {{- if eq $name "frontend" }}
      nodePort: {{ $config.nodePort }}
      {{- end }}