{{- $name := .Values.component }}
{{- $config := index .Values $name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ $name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
