component: frontend
namespace: test

frontend:
  image: lusalvi/frontend
  tag: test
  imagePullPolicy: Always
  port: 80
  supabase:
    url: "https://clrawfedwpvywhdcclk.supabase.co"
    tablePrefix: "test_"

personal:
  image: lusalvi/personal
  tag: test
  imagePullPolicy: Always
  port: 3000
  supabase:
    url: "https://clrawfedwpvywhdcclk.supabase.co"
    tablePrefix: "test_"

vehiculos:
  image: lusalvi/vehiculos
  tag: test
  imagePullPolicy: Always
  port: 3000
  supabase:
    url: "https://clrawfedwpvywhdcclk.supabase.co"
    tablePrefix: "test_"

ingress:
  host: nuvexa-test.local
  rewrite: /$2

