component: frontend

frontend:
  image: lusalvi/frontend:latest
  port: 80
  nodePort: 30100
  supabase:
    url: "https://clrawfedwpvywhdcclk.supabase.co"
    tablePrefix: ""
    secretName: supabase-secret
    secretKey: SUPABASE_KEY

personal:
  image: lusalvi/personal:latest
  port: 3000
  supabase:
    url: "https://clrawfedwpvywhdcclk.supabase.co"
    tablePrefix: ""
    secretName: supabase-secret
    secretKey: SUPABASE_KEY

vehiculos:
  image: lusalvi/vehiculos:latest
  port: 3000
  supabase:
    url: "https://clrawfedwpvywhdcclk.supabase.co"
    tablePrefix: ""
    secretName: supabase-secret
    secretKey: SUPABASE_KEY

ingress:
  host: ""
  rewrite: /
  paths:
    - path: /
      service: frontend
      port: 80
    - path: /api/personal
      service: personal
      port: 3000
    - path: /api/vehiculos
      service: vehiculos
      port: 3000
