component: frontend
namespace: test

frontend:
  image: lusalvi/frontend:test
  supabase:
    url: "https://clrawfedwpvywhdcclk.supabase.co"
    tablePrefix: "test_"

personal:
  image: lusalvi/personal:test
  supabase:
    url: "https://clrawfedwpvywhdcclk.supabase.co"
    tablePrefix: "test_"

vehiculos:
  image: lusalvi/vehiculos:test
  supabase:
    url: "https://clrawfedwpvywhdcclk.supabase.co"
    tablePrefix: "test_"

ingress:
  host: nuvexa-test.local
  rewrite: /$2
